import type { Metadata } from 'next'
import './globals.css'
import { CssBaseline, ThemeProvider } from '@mui/material'
import { mainTheme } from '@/utils/theme'

export const metadata: Metadata = {
    title: 'Syneps Academy - Sekolah Jadi Programmer!',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <ThemeProvider theme={mainTheme}>
                    <CssBaseline />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}
